export const teamMembers = [
  {
    id: "maya",
    name: "Maya Chen",
    initials: "MC",
    email: "maya@teamtask.test",
    role: "Owner",
    joined: "Apr 12, 2026",
    tone: "",
    workload: 72,
    focus: "Authentication and project direction",
  },
  {
    id: "niran",
    name: "Niran Patel",
    initials: "NP",
    email: "niran@teamtask.test",
    role: "Admin",
    joined: "Apr 14, 2026",
    tone: "purple",
    workload: 58,
    focus: "Organizations and permissions",
  },
  {
    id: "lena",
    name: "Lena Ortiz",
    initials: "LO",
    email: "lena@teamtask.test",
    role: "Member",
    joined: "Apr 15, 2026",
    tone: "orange",
    workload: 81,
    focus: "Task filters and API review",
  },
  {
    id: "sam",
    name: "Sam Rivera",
    initials: "SR",
    email: "sam@teamtask.test",
    role: "Member",
    joined: "Apr 17, 2026",
    tone: "blue",
    workload: 44,
    focus: "Dashboard and static prototype",
  },
] as const;

export const projects = [
  {
    id: "frontend-integration",
    title: "Frontend Integration",
    description: "Connect V1 screens to the future Next.js frontend and API modules.",
    status: "Active",
    due: "Due May 14",
    tasks: 24,
    progress: 62,
    members: ["maya", "niran", "lena"],
  },
  {
    id: "authentication",
    title: "Authentication",
    description: "Register, login, JWT session handling, protected routes, and profile basics.",
    status: "Active",
    due: "Due Apr 29",
    tasks: 11,
    progress: 76,
    members: ["maya", "sam"],
  },
  {
    id: "organization-management",
    title: "Organization Management",
    description: "Workspace creation, member roles, permissions, and owner controls.",
    status: "Planning",
    due: "Due May 8",
    tasks: 9,
    progress: 34,
    members: ["niran", "lena"],
  },
  {
    id: "dashboard-reporting",
    title: "Dashboard Reporting",
    description: "Summary widgets, recent activity, search, filters, and report exports.",
    status: "Review",
    due: "Due May 18",
    tasks: 14,
    progress: 51,
    members: ["sam", "maya"],
  },
] as const;

export const tasks = [
  {
    id: "jwt-login-flow",
    title: "Implement JWT login flow",
    description: "Build login endpoint, token response shape, and protected route checks.",
    projectId: "authentication",
    assigneeId: "maya",
    priority: "High",
    status: "In progress",
    due: "Apr 29, 2026",
    dueDate: "2026-04-29",
    comments: 4,
    attachments: 2,
    progress: 65,
  },
  {
    id: "organization-crud",
    title: "Create organization CRUD",
    description: "Workspace model, owner state, and role checks.",
    projectId: "organization-management",
    assigneeId: "niran",
    priority: "Medium",
    status: "To do",
    due: "May 2, 2026",
    dueDate: "2026-05-02",
    comments: 2,
    attachments: 1,
    progress: 20,
  },
  {
    id: "task-filter-query",
    title: "Review task filter query params",
    description: "Status, priority, assignee, due date, sorting, and pagination.",
    projectId: "frontend-integration",
    assigneeId: "lena",
    priority: "Medium",
    status: "Review",
    due: "May 4, 2026",
    dueDate: "2026-05-04",
    comments: 5,
    attachments: 0,
    progress: 88,
  },
  {
    id: "static-prototype-shell",
    title: "Build static prototype shell",
    description: "HTML, CSS, and JavaScript foundation for the app UI.",
    projectId: "frontend-integration",
    assigneeId: "sam",
    priority: "Low",
    status: "Done",
    due: "Apr 24, 2026",
    dueDate: "2026-04-24",
    comments: 3,
    attachments: 3,
    progress: 100,
  },
  {
    id: "api-error-contract",
    title: "Write API error response contract",
    description: "Define consistent error payloads for frontend integration.",
    projectId: "dashboard-reporting",
    assigneeId: "maya",
    priority: "High",
    status: "To do",
    due: "May 6, 2026",
    dueDate: "2026-05-06",
    comments: 1,
    attachments: 0,
    progress: 10,
  },
  {
    id: "member-permission-matrix",
    title: "Validate member permission matrix",
    description: "Confirm owner, admin, and member behavior before API work.",
    projectId: "organization-management",
    assigneeId: "niran",
    priority: "Medium",
    status: "In progress",
    due: "May 9, 2026",
    dueDate: "2026-05-09",
    comments: 6,
    attachments: 1,
    progress: 54,
  },
] as const;

export const activity = [
  {
    memberId: "sam",
    title: "Sam completed prototype shell",
    description: "Static HTML, CSS, and JavaScript are ready.",
    time: "10 min ago",
  },
  {
    memberId: "maya",
    title: "Maya added auth notes",
    description: "Error states and protected route behavior documented.",
    time: "1 hr ago",
  },
  {
    memberId: "niran",
    title: "Niran moved role matrix to review",
    description: "Owner, admin, and member permissions are ready for validation.",
    time: "3 hrs ago",
  },
  {
    memberId: "lena",
    title: "Lena uploaded ERD notes",
    description: "Users, organizations, projects, tasks, assignees, and comments are mapped.",
    time: "Yesterday",
  },
] as const;

export const calendarEvents = [
  { date: "Apr 29", title: "JWT login flow", type: "Deadline", ownerId: "maya" },
  { date: "May 2", title: "Organization CRUD", type: "Milestone", ownerId: "niran" },
  { date: "May 4", title: "Task filter API review", type: "Review", ownerId: "lena" },
  { date: "May 8", title: "Workspace role check", type: "Review", ownerId: "niran" },
  { date: "May 14", title: "Frontend integration demo", type: "Demo", ownerId: "sam" },
] as const;

export const files = [
  ["ERD draft", "architecture.md", "Niran Patel", "Apr 24"],
  ["API response contract", "api-errors.md", "Maya Chen", "Apr 25"],
  ["Dashboard screenshots", "dashboard-reference.zip", "Sam Rivera", "Apr 25"],
  ["Task filter examples", "task-query-cases.csv", "Lena Ortiz", "Apr 26"],
] as const;

export const automations = [
  ["High priority due today", "Send owner reminder and mark risk", "Active"],
  ["Task moved to review", "Notify project admins", "Active"],
  ["Project reaches 90%", "Create release checklist", "Draft"],
  ["Member overloaded", "Notify workspace owner", "Paused"],
] as const;

export const clientReviews = [
  ["Frontend dashboard preview", "Waiting for client", "May 12"],
  ["Auth flow copy", "Approved", "Apr 28"],
  ["Task board behavior", "Internal review", "May 6"],
] as const;

export const timelineMilestones = [
  ["Apr 24", "Static prototype shell", "Done", 100],
  ["Apr 29", "Authentication flow", "In progress", 76],
  ["May 8", "Organization and permissions", "Planning", 34],
  ["May 14", "Frontend integration demo", "Active", 62],
  ["May 18", "Dashboard reporting review", "Review", 51],
] as const;
