export const referenceScreens = [
  {
    slug: "dashboard-overview",
    title: "Dashboard Overview",
    kicker: "Overview",
    description: "Executive summary with metrics and activity.",
    image: "/images/previews/dashboard_overview.png",
    tags: "dashboard overview metrics activity",
  },
  {
    slug: "project-kanban-board",
    title: "Project Kanban Board",
    kicker: "Projects",
    description: "Column-based task planning.",
    image: "/images/previews/project_kanban_board.png",
    tags: "project kanban board tasks columns workflow",
  },
  {
    slug: "my-tasks-overview",
    title: "My Tasks Overview",
    kicker: "Tasks",
    description: "Personal assignments and priorities.",
    image: "/images/previews/my_tasks_overview.png",
    tags: "my tasks overview personal assignments",
  },
  {
    slug: "task-details-view",
    title: "Task Details View",
    kicker: "Tasks",
    description: "Detailed collaboration context.",
    image: "/images/previews/task_details_view.png",
    tags: "task details comments activity",
  },
  {
    slug: "team-schedule-calendar",
    title: "Team Schedule Calendar",
    kicker: "Schedule",
    description: "Meetings, milestones, and planning.",
    image: "/images/previews/team_schedule_calendar.png",
    tags: "team schedule calendar planning dates",
  },
  {
    slug: "project-timeline-gantt",
    title: "Project Timeline Gantt",
    kicker: "Timeline",
    description: "Roadmap and dependencies.",
    image: "/images/previews/project_timeline_gantt.png",
    tags: "project timeline gantt milestones roadmap",
  },
  {
    slug: "team-workload-management",
    title: "Team Workload Management",
    kicker: "Team",
    description: "Capacity visibility by member.",
    image: "/images/previews/team_workload_management.png",
    tags: "team workload management capacity people",
  },
  {
    slug: "analytics-reports",
    title: "Analytics Reports",
    kicker: "Insights",
    description: "Performance and trend reporting.",
    image: "/images/previews/analytics_reports.png",
    tags: "analytics reports charts data performance",
  },
  {
    slug: "automation-engine",
    title: "Automation Engine",
    kicker: "Automation",
    description: "Rules and workflow automation.",
    image: "/images/previews/automation_engine.png",
    tags: "automation engine rules triggers actions",
  },
  {
    slug: "file-asset-library",
    title: "File Asset Library",
    kicker: "Assets",
    description: "Shared project resources.",
    image: "/images/previews/file_asset_library.png",
    tags: "file asset library documents files resources",
  },
  {
    slug: "client-review-portal",
    title: "Client Review Portal",
    kicker: "Clients",
    description: "Feedback and approvals.",
    image: "/images/previews/client_review_portal.png",
    tags: "client review portal approvals external feedback",
  },
  {
    slug: "user-onboarding",
    title: "User Onboarding",
    kicker: "Setup",
    description: "Workspace setup flow.",
    image: "/images/previews/user_onboarding.png",
    tags: "user onboarding setup organization workspace",
  },
] as const;

export type ReferenceScreenSlug = (typeof referenceScreens)[number]["slug"];
