export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  projects: "/projects",
  tasks: "/tasks",
  myTasks: "/my-tasks",
  members: "/members",
  calendar: "/calendar",
  timeline: "/timeline",
  analytics: "/analytics",
  activity: "/activity",
  workload: "/workload",
  files: "/files",
  automation: "/automation",
  clients: "/clients",
  reference: "/reference",
  profile: "/settings/profile",
  workspaceSettings: "/settings/workspace",
} as const;
